#!/usr/bin/python3
# -*- coding: utf-8; tab-width: 4; indent-tabs-mode: t -*-

import os
import sys
import shutil
import tempfile
import argparse
sys.path.append('/usr/lib/sync-up-daemon')
from gbs_util import GbsUtil
from gbs_param import GbsParam
from gbs_httpd import GbsHttpDaemon


# parse parameter
parseResult = None
if True:
    argParser = argparse.ArgumentParser()
    argParser.add_argument("--protocol", choices=['HTTP', 'HTTPS'], help="Specify protocol.")
    argParser.add_argument("--port", help="Specify listening port.")
    argParser.add_argument("--auth-type", dest='auth_type',
                           choices=['NONE', 'HTPASSWD'], help="Specify authencation type.")
    argParser.add_argument("--pid-file", dest='pid_file', help="Specify location of a PID file.")
    argParser.add_argument("-d", "--debug-level", dest='debug_level',
                           choices=['CRITICAL', 'ERROR', 'WARNING', 'INFO', 'DEBUG'], default="INFO",
                           help="Set output debug message level")
    parseResult = argParser.parse_args()


param = GbsParam()
try:
    # fill GbsParam according to argument
    if parseResult.protocol is not None:
        param.protocol = parseResult.protocol
    else:
        param.protocol = "HTTP"
    if parseResult.port is not None:
        param.port = parseResult.port
    else:
        if param.protocol == "HTTP":
            param.port = 80
        elif param.protocol == "HTTPS":
            param.port = 443
        else:
            assert False
    if parseResult.auth_type is not None:
        param.authType = parseResult.auth_type
    else:
        param.authType = "NONE"
    if parseResult.pid_file is not None:
        param.pidFile = parseResult.pid_file
    param.logLevel = parseResult.debug_level

    # create directories
    param.tmpDir = tempfile.mkdtemp(prefix="sync-up-daemon-")
    GbsUtil.chown(param.tmpDir, param.user, param.group)
    GbsUtil.mkDirAndClear(param.webRootDir)
    GbsUtil.chown(param.webRootDir, param.user, param.group)

    # start server
    GbsDaemon(param).run().wait()
finally:
    if param.tmpDir is not None and os.path.exists(param.tmpDir):
        shutil.rmtree(param.tmpDir)
    if os.path.exists(param.runDir):
        shutil.rmtree(param.runDir)
